### ISSUE TITLE
Issue running sandbox

### ISSUE THREAD

**Issue by pablojordandlf** [algorand/auction-demo#4]
Hi! Sorry I'm kind of new in this. When I'm trying to run sandbox ( _./sandbox up_ ), it asks me with program do I want to use to open it (btw, I'm in a Windows PC). What should I choose/install?

**Comment by barnjamin** [comment]
Hi! Make sure you have all the pre-requisites installed here: https://github.com/algorand/sandbox

You may use whatever network you'd like but `./sandbox up release` should work best
